fix: DNS firewall VPC association priority (#427)
Update the priority so that it is between 100 and 9900.  Error received on last
TF apply was:

```
Error: error creating Route 53 Resolver DNS Firewall rule group association:
ValidationException: [RSLVR-02017] The priority value you provided is reserved.
Provide a number between "100" and "9900"
```